"""
Theme & Palette System — Complete coordinated color theme presets for Jayraldine's Catering System.
Supports background, surface, sidebar, text, borders, and accents organized by:
1. Nature-inspired
2. Mood/Tone-based
3. Color-driven
4. Vibe-based
5. Seasonal
"""

THEME_CATEGORIES = [
    "Mood/Tone-based",
    "Nature-inspired",
    "Color-driven",
    "Vibe-based",
    "Seasonal"
]

THEME_PALETTES = {
    # ── 1. MOOD / TONE-BASED ──────────────────────────────────────────────────
    "dark_mode": {
        "id": "dark_mode",
        "name": "Dark Mode",
        "category": "Mood/Tone-based",
        "mode": "dark",
        "primary": "#E11D48",
        "primary_hover": "#BE123C",
        "background": "#0F172A",
        "surface": "#1E293B",
        "surface_hover": "#243244",
        "sidebar_bg": "#111827",
        "sidebar_hover": "rgba(225, 29, 72, 0.12)",
        "sidebar_active": "#E11D48",
        "text_primary": "#F8FAFC",
        "text_secondary": "#94A3B8",
        "border": "#334155",
        "input_bg": "#0F172A",
    },
    "light_mode": {
        "id": "light_mode",
        "name": "Light Mode",
        "category": "Mood/Tone-based",
        "mode": "light",
        "primary": "#E11D48",
        "primary_hover": "#BE123C",
        "background": "#F1F5F9",
        "surface": "#FFFFFF",
        "surface_hover": "#F8FAFC",
        "sidebar_bg": "#FFFFFF",
        "sidebar_hover": "rgba(225, 29, 72, 0.08)",
        "sidebar_active": "#E11D48",
        "text_primary": "#0F172A",
        "text_secondary": "#64748B",
        "border": "#E2E8F0",
        "input_bg": "#FFFFFF",
    },
    "midnight": {
        "id": "midnight",
        "name": "Midnight (Deep Dark)",
        "category": "Mood/Tone-based",
        "mode": "dark",
        "primary": "#6366F1",
        "primary_hover": "#4F46E5",
        "background": "#05070E",
        "surface": "#0C101D",
        "surface_hover": "#131A2E",
        "sidebar_bg": "#080B14",
        "sidebar_hover": "rgba(99, 102, 241, 0.15)",
        "sidebar_active": "#6366F1",
        "text_primary": "#F8FAFC",
        "text_secondary": "#818CF8",
        "border": "#1E293B",
        "input_bg": "#070A12",
    },
    "daylight": {
        "id": "daylight",
        "name": "Daylight",
        "category": "Mood/Tone-based",
        "mode": "light",
        "primary": "#0284C7",
        "primary_hover": "#0369A1",
        "background": "#F0F9FF",
        "surface": "#FFFFFF",
        "surface_hover": "#E0F2FE",
        "sidebar_bg": "#F8FAFC",
        "sidebar_hover": "rgba(2, 132, 199, 0.10)",
        "sidebar_active": "#0284C7",
        "text_primary": "#0C4A6E",
        "text_secondary": "#0284C7",
        "border": "#BAE6FD",
        "input_bg": "#FFFFFF",
    },
    "twilight": {
        "id": "twilight",
        "name": "Twilight",
        "category": "Mood/Tone-based",
        "mode": "dark",
        "primary": "#A855F7",
        "primary_hover": "#9333EA",
        "background": "#120E1E",
        "surface": "#1E1830",
        "surface_hover": "#2A2242",
        "sidebar_bg": "#0D0A16",
        "sidebar_hover": "rgba(168, 85, 247, 0.15)",
        "sidebar_active": "#A855F7",
        "text_primary": "#FAF5FF",
        "text_secondary": "#C084FC",
        "border": "#3B2D54",
        "input_bg": "#140F21",
    },
    "monochrome": {
        "id": "monochrome",
        "name": "Monochrome",
        "category": "Mood/Tone-based",
        "mode": "dark",
        "primary": "#E2E8F0",
        "primary_hover": "#CBD5E1",
        "background": "#121212",
        "surface": "#1E1E1E",
        "surface_hover": "#2A2A2A",
        "sidebar_bg": "#181818",
        "sidebar_hover": "rgba(255, 255, 255, 0.10)",
        "sidebar_active": "#383838",
        "text_primary": "#FFFFFF",
        "text_secondary": "#A3A3A3",
        "border": "#333333",
        "input_bg": "#141414",
    },
    "high_contrast": {
        "id": "high_contrast",
        "name": "High Contrast",
        "category": "Mood/Tone-based",
        "mode": "dark",
        "primary": "#FACC15",
        "primary_hover": "#EAB308",
        "background": "#000000",
        "surface": "#0A0A0A",
        "surface_hover": "#171717",
        "sidebar_bg": "#000000",
        "sidebar_hover": "rgba(250, 204, 21, 0.20)",
        "sidebar_active": "#FACC15",
        "text_primary": "#FFFFFF",
        "text_secondary": "#FDE047",
        "border": "#FACC15",
        "input_bg": "#000000",
    },

    # ── 2. NATURE-INSPIRED ────────────────────────────────────────────────────
    "ocean_blue": {
        "id": "ocean_blue",
        "name": "Ocean Blue",
        "category": "Nature-inspired",
        "mode": "dark",
        "primary": "#0EA5E9",
        "primary_hover": "#0284C7",
        "background": "#0A192F",
        "surface": "#112240",
        "surface_hover": "#1D3557",
        "sidebar_bg": "#061224",
        "sidebar_hover": "rgba(14, 165, 233, 0.15)",
        "sidebar_active": "#0EA5E9",
        "text_primary": "#F0F9FF",
        "text_secondary": "#7DD3FC",
        "border": "#233D60",
        "input_bg": "#0C1B33",
    },
    "forest_green": {
        "id": "forest_green",
        "name": "Forest Green",
        "category": "Nature-inspired",
        "mode": "dark",
        "primary": "#10B981",
        "primary_hover": "#059669",
        "background": "#061A14",
        "surface": "#0C2E24",
        "surface_hover": "#144234",
        "sidebar_bg": "#04120E",
        "sidebar_hover": "rgba(16, 185, 129, 0.15)",
        "sidebar_active": "#10B981",
        "text_primary": "#ECFDF5",
        "text_secondary": "#6EE7B7",
        "border": "#1A4D3E",
        "input_bg": "#08211A",
    },
    "sunset_orange": {
        "id": "sunset_orange",
        "name": "Sunset Orange",
        "category": "Nature-inspired",
        "mode": "dark",
        "primary": "#F97316",
        "primary_hover": "#EA580C",
        "background": "#1A0F0A",
        "surface": "#2D1B13",
        "surface_hover": "#3E261B",
        "sidebar_bg": "#140B07",
        "sidebar_hover": "rgba(249, 115, 22, 0.15)",
        "sidebar_active": "#F97316",
        "text_primary": "#FFF7ED",
        "text_secondary": "#FDBA74",
        "border": "#4D2F22",
        "input_bg": "#1F120C",
    },
    "desert_sand": {
        "id": "desert_sand",
        "name": "Desert Sand",
        "category": "Nature-inspired",
        "mode": "light",
        "primary": "#D97706",
        "primary_hover": "#B45309",
        "background": "#FDFBF7",
        "surface": "#F6F0E6",
        "surface_hover": "#EDE2D0",
        "sidebar_bg": "#F0E7D8",
        "sidebar_hover": "rgba(217, 119, 6, 0.12)",
        "sidebar_active": "#D97706",
        "text_primary": "#451A03",
        "text_secondary": "#92400E",
        "border": "#E6D5BC",
        "input_bg": "#FFFFFF",
    },
    "midnight_sky": {
        "id": "midnight_sky",
        "name": "Midnight Sky",
        "category": "Nature-inspired",
        "mode": "dark",
        "primary": "#38BDF8",
        "primary_hover": "#0284C7",
        "background": "#030B17",
        "surface": "#0B192C",
        "surface_hover": "#142842",
        "sidebar_bg": "#020710",
        "sidebar_hover": "rgba(56, 189, 248, 0.15)",
        "sidebar_active": "#38BDF8",
        "text_primary": "#F0F9FF",
        "text_secondary": "#94A3B8",
        "border": "#1E3E62",
        "input_bg": "#071221",
    },
    "aurora": {
        "id": "aurora",
        "name": "Aurora",
        "category": "Nature-inspired",
        "mode": "dark",
        "primary": "#2DD4BF",
        "primary_hover": "#14B8A6",
        "background": "#04151B",
        "surface": "#0C2932",
        "surface_hover": "#133D4A",
        "sidebar_bg": "#031015",
        "sidebar_hover": "rgba(45, 212, 191, 0.15)",
        "sidebar_active": "#2DD4BF",
        "text_primary": "#F0FDFA",
        "text_secondary": "#5EEAD4",
        "border": "#1B4F5E",
        "input_bg": "#071D25",
    },
    "coral_reef": {
        "id": "coral_reef",
        "name": "Coral Reef",
        "category": "Nature-inspired",
        "mode": "dark",
        "primary": "#FB7185",
        "primary_hover": "#F43F5E",
        "background": "#1A0E14",
        "surface": "#2C1722",
        "surface_hover": "#3E2130",
        "sidebar_bg": "#140A0F",
        "sidebar_hover": "rgba(251, 113, 133, 0.15)",
        "sidebar_active": "#FB7185",
        "text_primary": "#FFF1F2",
        "text_secondary": "#FDA4AF",
        "border": "#4E2B3C",
        "input_bg": "#201119",
    },
    "mountain_mist": {
        "id": "mountain_mist",
        "name": "Mountain Mist",
        "category": "Nature-inspired",
        "mode": "light",
        "primary": "#475569",
        "primary_hover": "#334155",
        "background": "#F1F5F9",
        "surface": "#E2E8F0",
        "surface_hover": "#CBD5E1",
        "sidebar_bg": "#E2E8F0",
        "sidebar_hover": "rgba(71, 85, 105, 0.12)",
        "sidebar_active": "#475569",
        "text_primary": "#0F172A",
        "text_secondary": "#475569",
        "border": "#CBD5E1",
        "input_bg": "#FFFFFF",
    },

    # ── 3. COLOR-DRIVEN ───────────────────────────────────────────────────────
    "royal_purple": {
        "id": "royal_purple",
        "name": "Royal Purple",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#9333EA",
        "primary_hover": "#7E22CE",
        "background": "#130A24",
        "surface": "#20123A",
        "surface_hover": "#2E1A52",
        "sidebar_bg": "#0D0719",
        "sidebar_hover": "rgba(147, 51, 234, 0.15)",
        "sidebar_active": "#9333EA",
        "text_primary": "#FAF5FF",
        "text_secondary": "#D8B4FE",
        "border": "#3E246C",
        "input_bg": "#180D2D",
    },
    "ruby_red": {
        "id": "ruby_red",
        "name": "Ruby Red",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#DC2626",
        "primary_hover": "#B91C1C",
        "background": "#180A0A",
        "surface": "#2A1212",
        "surface_hover": "#3D1A1A",
        "sidebar_bg": "#120606",
        "sidebar_hover": "rgba(220, 38, 38, 0.15)",
        "sidebar_active": "#DC2626",
        "text_primary": "#FEF2F2",
        "text_secondary": "#FCA5A5",
        "border": "#4F2121",
        "input_bg": "#1F0D0D",
    },
    "emerald": {
        "id": "emerald",
        "name": "Emerald",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#059669",
        "primary_hover": "#047857",
        "background": "#061A14",
        "surface": "#0F2E23",
        "surface_hover": "#174435",
        "sidebar_bg": "#04120E",
        "sidebar_hover": "rgba(5, 150, 105, 0.15)",
        "sidebar_active": "#059669",
        "text_primary": "#ECFDF5",
        "text_secondary": "#6EE7B7",
        "border": "#1E5844",
        "input_bg": "#0A221A",
    },
    "sapphire": {
        "id": "sapphire",
        "name": "Sapphire",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#2563EB",
        "primary_hover": "#1D4ED8",
        "background": "#08132B",
        "surface": "#10224A",
        "surface_hover": "#18326B",
        "sidebar_bg": "#050C1C",
        "sidebar_hover": "rgba(37, 99, 235, 0.15)",
        "sidebar_active": "#2563EB",
        "text_primary": "#EFF6FF",
        "text_secondary": "#93C5FD",
        "border": "#21428B",
        "input_bg": "#0B1B3C",
    },
    "amber_gold": {
        "id": "amber_gold",
        "name": "Amber Gold",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#F59E0B",
        "primary_hover": "#D97706",
        "background": "#1A1408",
        "surface": "#2C220E",
        "surface_hover": "#3E3014",
        "sidebar_bg": "#120E05",
        "sidebar_hover": "rgba(245, 158, 11, 0.15)",
        "sidebar_active": "#F59E0B",
        "text_primary": "#FFFBEB",
        "text_secondary": "#FCD34D",
        "border": "#523F1A",
        "input_bg": "#21190A",
    },
    "rose_gold": {
        "id": "rose_gold",
        "name": "Rose Gold",
        "category": "Color-driven",
        "mode": "light",
        "primary": "#E11D48",
        "primary_hover": "#BE123C",
        "background": "#FFF5F7",
        "surface": "#FFE4E8",
        "surface_hover": "#FECDD6",
        "sidebar_bg": "#FFE4E8",
        "sidebar_hover": "rgba(225, 29, 72, 0.12)",
        "sidebar_active": "#E11D48",
        "text_primary": "#881337",
        "text_secondary": "#BE123C",
        "border": "#FDA4AF",
        "input_bg": "#FFFFFF",
    },
    "slate_gray": {
        "id": "slate_gray",
        "name": "Slate Gray",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#94A3B8",
        "primary_hover": "#64748B",
        "background": "#0F172A",
        "surface": "#1E293B",
        "surface_hover": "#334155",
        "sidebar_bg": "#0B1120",
        "sidebar_hover": "rgba(148, 163, 184, 0.15)",
        "sidebar_active": "#475569",
        "text_primary": "#F8FAFC",
        "text_secondary": "#CBD5E1",
        "border": "#334155",
        "input_bg": "#131E35",
    },
    "charcoal": {
        "id": "charcoal",
        "name": "Charcoal",
        "category": "Color-driven",
        "mode": "dark",
        "primary": "#E5E7EB",
        "primary_hover": "#D1D5DB",
        "background": "#18181B",
        "surface": "#27272A",
        "surface_hover": "#3F3F46",
        "sidebar_bg": "#09090B",
        "sidebar_hover": "rgba(229, 231, 235, 0.10)",
        "sidebar_active": "#3F3F46",
        "text_primary": "#FAFAFA",
        "text_secondary": "#A1A1AA",
        "border": "#3F3F46",
        "input_bg": "#1C1C1F",
    },

    # ── 4. VIBE-BASED ─────────────────────────────────────────────────────────
    "minimalist": {
        "id": "minimalist",
        "name": "Minimalist",
        "category": "Vibe-based",
        "mode": "light",
        "primary": "#18181B",
        "primary_hover": "#27272A",
        "background": "#FAFAFA",
        "surface": "#FFFFFF",
        "surface_hover": "#F4F4F5",
        "sidebar_bg": "#FFFFFF",
        "sidebar_hover": "rgba(24, 24, 27, 0.06)",
        "sidebar_active": "#18181B",
        "text_primary": "#18181B",
        "text_secondary": "#71717A",
        "border": "#E4E4E7",
        "input_bg": "#FFFFFF",
    },
    "vibrant": {
        "id": "vibrant",
        "name": "Vibrant",
        "category": "Vibe-based",
        "mode": "dark",
        "primary": "#FF007A",
        "primary_hover": "#E5006D",
        "background": "#0F0C20",
        "surface": "#1A1538",
        "surface_hover": "#282055",
        "sidebar_bg": "#0B0918",
        "sidebar_hover": "rgba(255, 0, 122, 0.18)",
        "sidebar_active": "#FF007A",
        "text_primary": "#FFFFFF",
        "text_secondary": "#FF80BF",
        "border": "#3E3080",
        "input_bg": "#14102C",
    },
    "pastel": {
        "id": "pastel",
        "name": "Pastel",
        "category": "Vibe-based",
        "mode": "light",
        "primary": "#818CF8",
        "primary_hover": "#6366F1",
        "background": "#FAF5FF",
        "surface": "#F3E8FF",
        "surface_hover": "#E9D5FF",
        "sidebar_bg": "#FAF5FF",
        "sidebar_hover": "rgba(129, 140, 248, 0.15)",
        "sidebar_active": "#818CF8",
        "text_primary": "#3B0764",
        "text_secondary": "#7E22CE",
        "border": "#D8B4FE",
        "input_bg": "#FFFFFF",
    },
    "retro": {
        "id": "retro",
        "name": "Retro",
        "category": "Vibe-based",
        "mode": "dark",
        "primary": "#F59E0B",
        "primary_hover": "#D97706",
        "background": "#292524",
        "surface": "#44403C",
        "surface_hover": "#57534E",
        "sidebar_bg": "#1C1917",
        "sidebar_hover": "rgba(245, 158, 11, 0.18)",
        "sidebar_active": "#F59E0B",
        "text_primary": "#FAFAF9",
        "text_secondary": "#D6D3D1",
        "border": "#78716C",
        "input_bg": "#332F2C",
    },
    "cyberpunk": {
        "id": "cyberpunk",
        "name": "Cyberpunk / Neon",
        "category": "Vibe-based",
        "mode": "dark",
        "primary": "#00F0FF",
        "primary_hover": "#00C2CF",
        "background": "#050510",
        "surface": "#0C0C24",
        "surface_hover": "#171746",
        "sidebar_bg": "#03030D",
        "sidebar_hover": "rgba(0, 240, 255, 0.18)",
        "sidebar_active": "#00F0FF",
        "text_primary": "#00F0FF",
        "text_secondary": "#FF007F",
        "border": "#00F0FF",
        "input_bg": "#08081A",
    },
    "classic": {
        "id": "classic",
        "name": "Classic",
        "category": "Vibe-based",
        "mode": "dark",
        "primary": "#C084FC",
        "primary_hover": "#A855F7",
        "background": "#1E1B2E",
        "surface": "#2D2845",
        "surface_hover": "#3E375E",
        "sidebar_bg": "#151322",
        "sidebar_hover": "rgba(192, 132, 252, 0.15)",
        "sidebar_active": "#C084FC",
        "text_primary": "#F5F3FF",
        "text_secondary": "#DDD6FE",
        "border": "#4C4472",
        "input_bg": "#242037",
    },
    "corporate_blue": {
        "id": "corporate_blue",
        "name": "Corporate Blue",
        "category": "Vibe-based",
        "mode": "light",
        "primary": "#1D4ED8",
        "primary_hover": "#1E40AF",
        "background": "#F8FAFC",
        "surface": "#FFFFFF",
        "surface_hover": "#F1F5F9",
        "sidebar_bg": "#0F172A",
        "sidebar_hover": "rgba(29, 78, 216, 0.20)",
        "sidebar_active": "#1D4ED8",
        "text_primary": "#0F172A",
        "text_secondary": "#475569",
        "border": "#CBD5E1",
        "input_bg": "#FFFFFF",
    },
    "warm_earth": {
        "id": "warm_earth",
        "name": "Warm Earth",
        "category": "Vibe-based",
        "mode": "dark",
        "primary": "#EA580C",
        "primary_hover": "#C2410C",
        "background": "#1C1917",
        "surface": "#292524",
        "surface_hover": "#44403C",
        "sidebar_bg": "#12100E",
        "sidebar_hover": "rgba(234, 88, 12, 0.15)",
        "sidebar_active": "#EA580C",
        "text_primary": "#FAFAF9",
        "text_secondary": "#D6D3D1",
        "border": "#57534E",
        "input_bg": "#211D1A",
    },

    # ── 5. SEASONAL ───────────────────────────────────────────────────────────
    "spring_bloom": {
        "id": "spring_bloom",
        "name": "Spring Bloom",
        "category": "Seasonal",
        "mode": "light",
        "primary": "#EC4899",
        "primary_hover": "#DB2777",
        "background": "#FDF2F8",
        "surface": "#FCE7F3",
        "surface_hover": "#FBCFE8",
        "sidebar_bg": "#FCE7F3",
        "sidebar_hover": "rgba(236, 72, 153, 0.15)",
        "sidebar_active": "#EC4899",
        "text_primary": "#831843",
        "text_secondary": "#DB2777",
        "border": "#F9A8D4",
        "input_bg": "#FFFFFF",
    },
    "summer_breeze": {
        "id": "summer_breeze",
        "name": "Summer Breeze",
        "category": "Seasonal",
        "mode": "light",
        "primary": "#06B6D4",
        "primary_hover": "#0891B2",
        "background": "#ECFEFF",
        "surface": "#CFFAFE",
        "surface_hover": "#A5F3FC",
        "sidebar_bg": "#CFFAFE",
        "sidebar_hover": "rgba(6, 182, 212, 0.15)",
        "sidebar_active": "#06B6D4",
        "text_primary": "#164E63",
        "text_secondary": "#0891B2",
        "border": "#67E8F9",
        "input_bg": "#FFFFFF",
    },
    "autumn_harvest": {
        "id": "autumn_harvest",
        "name": "Autumn Harvest",
        "category": "Seasonal",
        "mode": "dark",
        "primary": "#D97706",
        "primary_hover": "#B45309",
        "background": "#1C140E",
        "surface": "#2E2117",
        "surface_hover": "#422F21",
        "sidebar_bg": "#140E0A",
        "sidebar_hover": "rgba(217, 119, 6, 0.15)",
        "sidebar_active": "#D97706",
        "text_primary": "#FFFBEB",
        "text_secondary": "#FBBF24",
        "border": "#583E2C",
        "input_bg": "#231912",
    },
    "winter_frost": {
        "id": "winter_frost",
        "name": "Winter Frost",
        "category": "Seasonal",
        "mode": "dark",
        "primary": "#67E8F9",
        "primary_hover": "#22D3EE",
        "background": "#071724",
        "surface": "#0E2A3E",
        "surface_hover": "#173E5A",
        "sidebar_bg": "#04101A",
        "sidebar_hover": "rgba(103, 232, 249, 0.15)",
        "sidebar_active": "#67E8F9",
        "text_primary": "#F0FDFA",
        "text_secondary": "#A5F3FC",
        "border": "#215378",
        "input_bg": "#091D2E",
    },
}


def get_palette(palette_id: str) -> dict:
    """Get palette dict by id, fallback to dark_mode."""
    return THEME_PALETTES.get(palette_id, THEME_PALETTES["dark_mode"])


def get_palettes_by_category() -> dict:
    """Returns {category_name: [palette_dicts]}."""
    grouped = {c: [] for c in THEME_CATEGORIES}
    for p in THEME_PALETTES.values():
        cat = p.get("category", "Mood/Tone-based")
        if cat not in grouped:
            grouped[cat] = []
        grouped[cat].append(p)
    return grouped
